/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
    const collection = app.findCollectionByNameOrId("abbreviations");

    const data = [
        { "acronym": "A1", "definition": "Act 1, mostly referring to Lioneye's Watch. Different number combinations are used for various acts (example: A4 refers to Act 4, usually Highgate)", "category": "General" },
        { "acronym": "AA", "definition": "Arctic Armour", "category": "General" },
        { "acronym": "AG", "definition": "Animate Guardian", "category": "General" },
        { "acronym": "Alch", "definition": "Orb of Alchemy", "category": "Currency" },
        { "acronym": "Alt", "definition": "Orb of Alteration", "category": "Currency" },
        { "acronym": "Alt ailments", "definition": "Alternative elemental ailments: Specifically brittle, scorch and sap", "category": "General" },
        { "acronym": "Ammy", "definition": "Amulet", "category": "General" },
        { "acronym": "AoE", "definition": "Area of effect", "category": "Map" },
        { "acronym": "AoF", "definition": "Avatar of Fire", "category": "General" },
        { "acronym": "APS", "definition": "Attacks per second", "category": "General" },
        { "acronym": "AR, arm", "definition": "Armour", "category": "General" },
        { "acronym": "AW", "definition": "Animate Weapon", "category": "General" },
        { "acronym": "AW", "definition": "Ancestral Warchief, no longer in the game", "category": "General" },
        { "acronym": "BB", "definition": "Blade Blast", "category": "General" },
        { "acronym": "Bench", "definition": "Non-Ruthless leagues", "category": "General" },
        { "acronym": "BF", "definition": "Bladefall", "category": "General" },
        { "acronym": "BF", "definition": "Blade Flurry", "category": "General" },
        { "acronym": "BiS", "definition": "Best in slot", "category": "General" },
        { "acronym": "BM", "definition": "Blood Magic keystone passive skill", "category": "General" },
        { "acronym": "BoR", "definition": "The Bringer of Rain", "category": "General" },
        { "acronym": "b/o", "definition": "Buyout (seller's asking price)", "category": "General" },
        { "acronym": "BR", "definition": "Blood Rage", "category": "General" },
        { "acronym": "Brick, bricked", "definition": "Using a Vaal Orb or other crafting method on an item and receiving an outcome that greatly decreases its value", "category": "Currency" },
        { "acronym": "BV", "definition": "Blade Vortex", "category": "General" },
        { "acronym": "c, chaos", "definition": "Chaos Orb", "category": "Currency" },
        { "acronym": "CA", "definition": "Caustic Arrow", "category": "General" },
        { "acronym": "CB", "definition": "Corrupted Blood", "category": "General" },
        { "acronym": "CF", "definition": "Corrupting Fever", "category": "General" },
        { "acronym": "CI", "definition": "Chaos Inoculation", "category": "General" },
        { "acronym": "CIP", "definition": "Cold Iron Point", "category": "General" },
        { "acronym": "cluster", "definition": "Cluster jewels", "category": "General" },
        { "acronym": "c/o", "definition": "Current Offer", "category": "General" },
        { "acronym": "CoC", "definition": "Cast On Critical Strike Support", "category": "Support" },
        { "acronym": "CoD", "definition": "Cast on Death Support", "category": "Support" },
        { "acronym": "CoE", "definition": "Crown of Eyes", "category": "General" },
        { "acronym": "CoH", "definition": "Hextouch Support, formerly named Curse on Hit Support", "category": "Support" },
        { "acronym": "CoMK", "definition": "Cast on Melee Kill Support", "category": "Support" },
        { "acronym": "Conc", "definition": "Concentrated Effect Support", "category": "Support" },
        { "acronym": "CotB, cotb", "definition": "Call of the Brotherhood", "category": "General" },
        { "acronym": "CwC", "definition": "Cast while Channelling Support", "category": "Support" },
        { "acronym": "CwDT", "definition": "Cast when Damage Taken Support", "category": "Support" },
        { "acronym": "DD", "definition": "Detonate Dead or other corpse explosion mechanics", "category": "General" },
        { "acronym": "Deli", "definition": "Delirium", "category": "General" },
        { "acronym": "Det, Determ", "definition": "Determination", "category": "General" },
        { "acronym": "Disc", "definition": "Discipline", "category": "General" },
        { "acronym": "div", "definition": "Divine Orb", "category": "Currency" },
        { "acronym": "div card", "definition": "Divination card", "category": "General" },
        { "acronym": "Dom", "definition": "Dominus", "category": "General" },
        { "acronym": "DoT", "definition": "Damage over time", "category": "General" },
        { "acronym": "DPS, Deeps", "definition": "Damage per second", "category": "General" },
        { "acronym": "DW", "definition": "Dual Wielding", "category": "General" },
        { "acronym": "EA", "definition": "Explosive Arrow", "category": "General" },
        { "acronym": "EB", "definition": "Eldritch Battery", "category": "General" },
        { "acronym": "EC", "definition": "Enduring Cry", "category": "General" },
        { "acronym": "Echo", "definition": "Spell Echo Support", "category": "Support" },
        { "acronym": "ED", "definition": "Essence Drain. \"ED/C\" is also used to refer to Essence Drain combined with Contagion.", "category": "General" },
        { "acronym": "eDPS", "definition": "Elemental Damage Per Second", "category": "General" },
        { "acronym": "EDwA", "definition": "Elemental Damage with Attacks Support or similarly worded modifiers to damage", "category": "Support" },
        { "acronym": "EE", "definition": "Elemental Equilibrium", "category": "General" },
        { "acronym": "eHP", "definition": "Effective Health / Hit Points / Pool, total number of damage that can be taken before death, after damage mitigations. (e.g. Combination of Life, Energy Shield, damage avoidance or mitigation)", "category": "General" },
        { "acronym": "EK", "definition": "Ethereal Knives", "category": "General" },
        { "acronym": "Ele", "definition": "Elemental", "category": "General" },
        { "acronym": "EO", "definition": "Elemental Overload", "category": "General" },
        { "acronym": "EoW", "definition": "Eye of Winter", "category": "General" },
        { "acronym": "EoW", "definition": "Eater of Worlds", "category": "General" },
        { "acronym": "EQ", "definition": "Earthquake", "category": "General" },
        { "acronym": "ES", "definition": "Energy Shield", "category": "General" },
        { "acronym": "Eva, EV", "definition": "Evasion", "category": "General" },
        { "acronym": "Ele Weak", "definition": "Elemental Weakness", "category": "General" },
        { "acronym": "Ex, exalted", "definition": "Exalted Orb", "category": "Currency" },
        { "acronym": "F", "definition": "Press F to Pay Respects. See RIP.", "category": "General" },
        { "acronym": "FA", "definition": "Faster Attacks Support", "category": "Support" },
        { "acronym": "FFA", "definition": "Free For All item allocation", "category": "Item" },
        { "acronym": "FB", "definition": "Facebreaker or Flameblast", "category": "General" },
        { "acronym": "Flat phys", "definition": "Added physical damage on gear (e.g. Adds 7-19 Physical Damage)", "category": "General" },
        { "acronym": "FP", "definition": "Freezing Pulse", "category": "General" },
        { "acronym": "FR", "definition": "Forbidden Rite", "category": "General" },
        { "acronym": "Fus, Fuse", "definition": "Orb of Fusing", "category": "Currency" },
        { "acronym": "GCP", "definition": "Gemcutter's Prism", "category": "General" },
        { "acronym": "GG", "definition": "Godly Gear items", "category": "General" },
        { "acronym": "GGG", "definition": "Grinding Gear Games", "category": "General" },
        { "acronym": "GH", "definition": "Glacial Hammer", "category": "General" },
        { "acronym": "GMP", "definition": "Greater Multiple Projectiles Support", "category": "Support" },
        { "acronym": "GR", "definition": "Ghost Reaver", "category": "General" },
        { "acronym": "HC", "definition": "Hardcore League", "category": "General" },
        { "acronym": "HFT", "definition": "Holy Flame Totem", "category": "General" },
        { "acronym": "HH", "definition": "Headhunter", "category": "General" },
        { "acronym": "HO, h/o", "definition": "Hideout", "category": "General" },
        { "acronym": "HoA", "definition": "Herald of Ash", "category": "General" },
        { "acronym": "HoAg", "definition": "Herald of Agony", "category": "General" },
        { "acronym": "HoI", "definition": "Herald of Ice", "category": "General" },
        { "acronym": "HoP", "definition": "Herald of Purity", "category": "General" },
        { "acronym": "HoT", "definition": "Herald of Thunder", "category": "General" },
        { "acronym": "HoWA", "definition": "Hand of Wisdom and Action", "category": "General" },
        { "acronym": "IL", "definition": "Inspired Learning", "category": "General" },
        { "acronym": "Inc AoE", "definition": "Increased Area of Effect Support", "category": "Support" },
        { "acronym": "IAS", "definition": "Increased attack speed", "category": "General" },
        { "acronym": "IC", "definition": "Immortal Call", "category": "General" },
        { "acronym": "Inc Dur", "definition": "More Duration Support", "category": "Support" },
        { "acronym": "IGN", "definition": "In-game Name", "category": "General" },
        { "acronym": "IIQ, quant", "definition": "Increased Item quantity", "category": "General" },
        { "acronym": "IIR, rarity", "definition": "Increased Item rarity", "category": "General" },
        { "acronym": "ilvl, i# (e.g. i83)", "definition": "Item level", "category": "Item" },
        { "acronym": "IPD", "definition": "Increased physical damage", "category": "General" },
        { "acronym": "IR", "definition": "Iron Reflexes", "category": "General" },
        { "acronym": "Jew", "definition": "Jeweller's Orb", "category": "Currency" },
        { "acronym": "Juice", "definition": "Harvest currencies such as Primal Crystallised Lifeforce (\"Blue Juice\"). Could also refer to making content more difficult and rewarding (\"juicing a map\").", "category": "General" },
        { "acronym": "Krangled", "definition": "Commonly refers to various ways items can become corrupted, including double corrupted and scourged. The term originates from a meme posted on the Path of Exile subreddit.[2]", "category": "General" },
        { "acronym": "Krangled", "definition": "Thoroughly disordered. See Krangled Passives.", "category": "General" },
        { "acronym": "LA", "definition": "Lightning Arrow", "category": "General" },
        { "acronym": "LL", "definition": "Low Life", "category": "General" },
        { "acronym": "LLD", "definition": "Low Level Dueling (level 28 or lower). Also used to refer to low level PvP events in general.", "category": "General" },
        { "acronym": "LMP", "definition": "Lesser Multiple Projectiles Support", "category": "Support" },
        { "acronym": "LS", "definition": "Lightning Strike", "category": "General" },
        { "acronym": "MB", "definition": "Mageblood or Magebane", "category": "General" },
        { "acronym": "MF", "definition": "Magic Finding (equivalent of increased item rarity in Diablo 2) - involves stacking IIR or IIQ", "category": "General" },
        { "acronym": "MI", "definition": "Minion Instability", "category": "General" },
        { "acronym": "Mods", "definition": "Modifiers", "category": "General" },
        { "acronym": "MoM", "definition": "Mind Over Matter", "category": "General" },
        { "acronym": "MS", "definition": "Movement Speed or Molten Shell", "category": "General" },
        { "acronym": "MTX, micro", "definition": "Microtransaction", "category": "General" },
        { "acronym": "MTX, micro", "definition": "More commonly refers to cosmetic items purchased from the microtransaction shop or included with supporter packs.", "category": "General" },
        { "acronym": "NA", "definition": "Necromantic Aegis", "category": "General" },
        { "acronym": "OOM", "definition": "Out of Mana", "category": "General" },
        { "acronym": "OOS", "definition": "Out of sync", "category": "General" },
        { "acronym": "OoS", "definition": "Orb of Storms", "category": "Currency" },
        { "acronym": "OP", "definition": "Original Poster (person who made the thread)", "category": "General" },
        { "acronym": "OP", "definition": "Overpowered (imbalanced)", "category": "General" },
        { "acronym": "PA", "definition": "Pain Attunement", "category": "General" },
        { "acronym": "PA", "definition": "Permanent Allocation", "category": "General" },
        { "acronym": "PB", "definition": "Point Blank", "category": "General" },
        { "acronym": "PB", "definition": "Petrified Blood", "category": "General" },
        { "acronym": "PC", "definition": "Price Check", "category": "General" },
        { "acronym": "PC", "definition": "Poisonous Concoction", "category": "General" },
        { "acronym": "PCoC", "definition": "Power Charge On Critical Support or other sources of power charges on critical strike", "category": "Support" },
        { "acronym": "PConc", "definition": "Poisonous Concoction", "category": "General" },
        { "acronym": "pDPS", "definition": "Physical damage per second", "category": "General" },
        { "acronym": "Pen", "definition": "Resistance penetration", "category": "General" },
        { "acronym": "Phys", "definition": "Physical damage", "category": "General" },
        { "acronym": "PoB", "definition": "Path of Building, an external software used to simulate character builds", "category": "General" },
        { "acronym": "PoE", "definition": "Path of Exile", "category": "General" },
        { "acronym": "PoE", "definition": "Purity of Elements", "category": "General" },
        { "acronym": "PoF", "definition": "Purity of Fire", "category": "General" },
        { "acronym": "PoI", "definition": "Purity of Ice", "category": "General" },
        { "acronym": "PoL", "definition": "Purity of Lightning", "category": "General" },
        { "acronym": "PotG, PotCG", "definition": "Pillar of the Caged God", "category": "General" },
        { "acronym": "Prolif", "definition": "Elemental Proliferation Support or proliferation in general", "category": "Support" },
        { "acronym": "PT", "definition": "Precise Technique", "category": "General" },
        { "acronym": "QotF", "definition": "Queen of the Forest", "category": "General" },
        { "acronym": "Quicksilver", "definition": "Quicksilver Flask", "category": "General" },
        { "acronym": "RIP", "definition": "Rest in Peace - mostly used as a synonym for \"death\", sometimes used as a verb. (e.g. \"I RIPed to the boss.\"), often used as an adjective to denote dangerous things likely to kill the player. (e.g. \"Delirium content can be really rippy\"). See F.", "category": "General" },
        { "acronym": "RMR, RE, res eff", "definition": "Reduced Mana Reserved or Reservation Efficiency - modifiers to reservation of skills", "category": "General" },
        { "acronym": "RNG", "definition": "Random Number Generator or Random Number Generation, i.e. randomness or chance", "category": "General" },
        { "acronym": "RoA", "definition": "Rain of Arrows", "category": "General" },
        { "acronym": "Rota", "definition": "Rotation, referring to players forming parties and taking turns, usually with each others' maps or keys (e.g. Poorjoy's Asylum rota, Chayula's Breachstone rota)", "category": "General" },
        { "acronym": "RF", "definition": "Righteous Fire", "category": "General" },
        { "acronym": "RT", "definition": "Resolute Technique", "category": "General" },
        { "acronym": "SA", "definition": "Split Arrow", "category": "General" },
        { "acronym": "SC", "definition": "Standard League or Softcore", "category": "General" },
        { "acronym": "Shavs", "definition": "Shavronne's Wrappings", "category": "General" },
        { "acronym": "Slam", "definition": "Slam skill", "category": "General" },
        { "acronym": "Slam", "definition": "To use an Exalted Orb or similar crafting method to add a random modifier to an item", "category": "Currency" },
        { "acronym": "SoS", "definition": "Secrets of Suffering", "category": "General" },
        { "acronym": "Spork", "definition": "Spark with Fork Support", "category": "General" },
        { "acronym": "SRS", "definition": "Summon Raging Spirit", "category": "General" },
        { "acronym": "SSF", "definition": "Solo Self-Found", "category": "General" },
        { "acronym": "SST", "definition": "Spectral Shield Throw", "category": "General" },
        { "acronym": "ST", "definition": "Spectral Throw", "category": "General" },
        { "acronym": "STD", "definition": "Standard permanent league", "category": "General" },
        { "acronym": "TC, Temp Chains", "definition": "Temporal Chains", "category": "General" },
        { "acronym": "Thread", "definition": "Thread of Hope", "category": "General" },
        { "acronym": "TP", "definition": "Town Portal, typically created with a Portal Scroll or Portal", "category": "General" },
        { "acronym": "TR", "definition": "Toxic Rain", "category": "General" },
        { "acronym": "TS", "definition": "Tornado Shot", "category": "General" },
        { "acronym": "US, Unwavering", "definition": "Unwavering Stance", "category": "General" },
        { "acronym": "Valdo", "definition": "Valdo's Puzzle Box, or a map obtained from one (\"a Valdo map\")", "category": "General" },
        { "acronym": "VC, Glad Block", "definition": "Versatile Combatant (formerly an Ascendancy Passive of the Gladiator Ascendancy)", "category": "General" },
        { "acronym": "VMS", "definition": "Vaal Molten Shell", "category": "General" },
        { "acronym": "VP", "definition": "Vaal Pact", "category": "General" },
        { "acronym": "WB", "definition": "Whirling Blades", "category": "General" },
        { "acronym": "WED", "definition": "Elemental Damage with Attacks Support, formerly named Weapon Elemental Damage Support. See EDwA.", "category": "Support" },
        { "acronym": "WoC", "definition": "Wave of Conviction", "category": "General" },
        { "acronym": "WP", "definition": "Waypoint", "category": "General" },
        { "acronym": "WTB", "definition": "Want To Buy", "category": "General" },
        { "acronym": "WTS", "definition": "Want To Sell", "category": "General" },
        { "acronym": "WTT", "definition": "Want To Trade", "category": "General" },
        { "acronym": "zDPS", "definition": "Zero DPS, describing builds or skills that do relatively little damage", "category": "General" },
        { "acronym": "ZO", "definition": "Zealot's Oath", "category": "General" },
        { "acronym": "Any combination of R, G, B", "definition": "The socket colors (Red, Green, Blue) on an item, typically also denoting the number of linked sockets. Numbers may preface colours in combination to determine total colours on an item - e.g. 4 linked item with 3 Red and 1 Blue sockets = 3R1B", "category": "General" },
        { "acronym": "L/Q gem", "definition": "Q : quality gem (# quality), L : level gem (# level) e.g.: 21/23 gem = level 21, 23 quality gem.", "category": "General" },
        { "acronym": "4L, 5L, 6L", "definition": "Number of item socket links", "category": "General" },
        { "acronym": "4S, 5S, 6S", "definition": "Number of item sockets", "category": "Item" }
    ];

    data.forEach(item => {
        try {
            // Check if record already exists to avoid duplicates
            // We use findFirstRecordByData which throws if not found
            app.findFirstRecordByData("abbreviations", "acronym", item.acronym);
        } catch (e) {
            // Record not found, create it
            const record = new Record(collection);
            record.set("acronym", item.acronym);
            record.set("definition", item.definition);
            record.set("category", item.category);
            app.save(record);
        }
    });

}, (app) => {
    // Down migration: we don't delete them because we don't know which ones were added by this specific migration vs others
    // and we don't want to delete user data if they added more.
})
