/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
    const collection = new Collection({
        "id": "abbreviations00",
        "created": "2025-12-02 21:30:00.000Z",
        "updated": "2025-12-02 21:30:00.000Z",
        "name": "abbreviations",
        "type": "base",
        "system": false,
        "fields": [
            {
                "autogeneratePattern": "",
                "hidden": false,
                "id": "abbr_acronym",
                "name": "acronym",
                "type": "text",
                "required": true,
                "presentable": true,
                "system": false,
                "min": null,
                "max": null,
                "pattern": ""
            },
            {
                "autogeneratePattern": "",
                "hidden": false,
                "id": "abbr_definition",
                "name": "definition",
                "type": "text",
                "required": true,
                "presentable": true,
                "system": false,
                "min": null,
                "max": null,
                "pattern": ""
            },
            {
                "autogeneratePattern": "",
                "hidden": false,
                "id": "abbr_category",
                "name": "category",
                "type": "text",
                "required": true,
                "presentable": true,
                "system": false,
                "min": null,
                "max": null,
                "pattern": ""
            }
        ],
        "indexes": [
            "CREATE INDEX `idx_abbr_acronym` ON `abbreviations` (`acronym`)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": null,
        "deleteRule": null,
        "options": {}
    });

    app.save(collection);

    const data = [
        { "acronym": "A1N", "definition": "Act 1 Normal (Historical)", "category": "Map/Zone" },
        { "acronym": "AA", "definition": "Arctic Armour", "category": "Skill" },
        { "acronym": "AC", "definition": "Ancestral Call", "category": "Support" },
        { "acronym": "AFK", "definition": "Away From Keyboard", "category": "Social" },
        { "acronym": "AG", "definition": "Animate Guardian", "category": "Skill" },
        { "acronym": "Aisling", "definition": "Syndicate Master (Veiled Slam)", "category": "Mechanic" },
        { "acronym": "Alch", "definition": "Orb of Alchemy", "category": "Currency" },
        { "acronym": "Alt", "definition": "Orb of Alteration", "category": "Currency" },
        { "acronym": "Annul", "definition": "Orb of Annulment", "category": "Currency" },
        { "acronym": "AoE", "definition": "Area of Effect", "category": "Mechanic" },
        { "acronym": "AoF", "definition": "Avatar of Fire", "category": "Keystone" },
        { "acronym": "APS", "definition": "Attacks Per Second", "category": "Stat" },
        { "acronym": "AR", "definition": "Armour Rating", "category": "Stat" },
        { "acronym": "Archmage", "definition": "Archmage Support", "category": "Support" },
        { "acronym": "Aug", "definition": "Orb of Augmentation", "category": "Currency" },
        { "acronym": "AW", "definition": "Animate Weapon / Ancestral Warchief", "category": "Skill" },
        { "acronym": "B/O", "definition": "Buyout", "category": "Trade" },
        { "acronym": "BAMA", "definition": "Blink Arrow / Mirror Arrow", "category": "Build" },
        { "acronym": "BB", "definition": "Blade Blast", "category": "Skill" },
        { "acronym": "BC", "definition": "Burial Chambers", "category": "Map" },
        { "acronym": "BF", "definition": "Blade Flurry / Bladefall", "category": "Skill" },
        { "acronym": "BiS", "definition": "Best in Slot", "category": "Item" },
        { "acronym": "BL", "definition": "Ball Lightning", "category": "Skill" },
        { "acronym": "Blight", "definition": "Blight Mechanic / Blight Spell", "category": "Mechanic" },
        { "acronym": "BM", "definition": "Blood Magic", "category": "Keystone" },
        { "acronym": "Bonk", "definition": "Slam Skills", "category": "Slang" },
        { "acronym": "BoR", "definition": "Bringer of Rain", "category": "Item" },
        { "acronym": "BP", "definition": "Blueprint (Heist)", "category": "Mechanic" },
        { "acronym": "BV", "definition": "Blade Vortex", "category": "Skill" },
        { "acronym": "C", "definition": "Chaos Orb", "category": "Currency" },
        { "acronym": "CA", "definition": "Caustic Arrow", "category": "Skill" },
        { "acronym": "CB", "definition": "Corrupted Blood", "category": "Debuff" },
        { "acronym": "CC", "definition": "Crowd Control (Freeze/Stun)", "category": "Mechanic" },
        { "acronym": "CD", "definition": "Cooldown", "category": "Stat" },
        { "acronym": "CDR", "definition": "Cooldown Recovery", "category": "Stat" },
        { "acronym": "CF", "definition": "Corrupting Fever", "category": "Skill" },
        { "acronym": "Chaos", "definition": "Chaos Orb", "category": "Currency" },
        { "acronym": "CI", "definition": "Chaos Inoculation", "category": "Keystone" },
        { "acronym": "CoC", "definition": "Cast On Critical Strike", "category": "Support" },
        { "acronym": "CoD", "definition": "Cast on Death", "category": "Support" },
        { "acronym": "CoH", "definition": "Curse on Hit (Hextouch)", "category": "Support" },
        { "acronym": "Conc", "definition": "Concentrated Effect", "category": "Support" },
        { "acronym": "CP", "definition": "Consecrated Path", "category": "Skill" },
        { "acronym": "CwC", "definition": "Cast while Channeling", "category": "Support" },
        { "acronym": "CwDT", "definition": "Cast when Damage Taken", "category": "Support" },
        { "acronym": "D", "definition": "Divine Orb", "category": "Currency" },
        { "acronym": "DB", "definition": "Dominating Blow", "category": "Skill" },
        { "acronym": "DD", "definition": "Detonate Dead", "category": "Skill" },
        { "acronym": "Deli", "definition": "Delirium", "category": "League" },
        { "acronym": "Div", "definition": "Divine Orb", "category": "Currency" },
        { "acronym": "DoT", "definition": "Damage over Time", "category": "Mechanic" },
        { "acronym": "DP", "definition": "Dark Pact", "category": "Skill" },
        { "acronym": "DPS", "definition": "Damage Per Second", "category": "Stat" },
        { "acronym": "DS", "definition": "Double Strike / Desync", "category": "Skill/Slang" },
        { "acronym": "DW", "definition": "Dual Wield", "category": "Mechanic" },
        { "acronym": "EA", "definition": "Explosive Arrow", "category": "Skill" },
        { "acronym": "EB", "definition": "Eldritch Battery", "category": "Keystone" },
        { "acronym": "EC", "definition": "Enduring Cry", "category": "Skill" },
        { "acronym": "Echo", "definition": "Spell Echo", "category": "Support" },
        { "acronym": "ED", "definition": "Essence Drain", "category": "Skill" },
        { "acronym": "eDPS", "definition": "Elemental DPS", "category": "Stat" },
        { "acronym": "EDWA", "definition": "Elemental Damage with Attacks", "category": "Support" },
        { "acronym": "EE", "definition": "Elemental Equilibrium", "category": "Keystone" },
        { "acronym": "eHP", "definition": "Effective Hit Points", "category": "Stat" },
        { "acronym": "EK", "definition": "Ethereal Knives", "category": "Skill" },
        { "acronym": "Ele", "definition": "Elemental / Elementalist", "category": "General" },
        { "acronym": "Enlighten", "definition": "Enlighten Support", "category": "Support" },
        { "acronym": "EO", "definition": "Elemental Overload", "category": "Keystone" },
        { "acronym": "EoW", "definition": "Eater of Worlds / Eye of Winter", "category": "Boss/Skill" },
        { "acronym": "EQ", "definition": "Earthquake", "category": "Skill" },
        { "acronym": "ES", "definition": "Energy Shield", "category": "Stat" },
        { "acronym": "Eva / EV", "definition": "Evasion Rating", "category": "Stat" },
        { "acronym": "Ex", "definition": "Exalted Orb", "category": "Currency" },
        { "acronym": "Exarch", "definition": "Searing Exarch", "category": "Boss" },
        { "acronym": "FA", "definition": "Faster Attacks", "category": "Support" },
        { "acronym": "FB", "definition": "Frost Blades / Fireball", "category": "Skill" },
        { "acronym": "FC", "definition": "Faster Casting", "category": "Support" },
        { "acronym": "Flip", "definition": "Market Manipulation", "category": "Trade" },
        { "acronym": "FP", "definition": "Freezing Pulse", "category": "Skill" },
        { "acronym": "FR", "definition": "Forbidden Rite", "category": "Skill" },
        { "acronym": "Fuse", "definition": "Orb of Fusing", "category": "Currency" },
        { "acronym": "GC", "definition": "Glacial Cascade", "category": "Skill" },
        { "acronym": "GCP", "definition": "Gemcutter's Prism", "category": "Currency" },
        { "acronym": "GG", "definition": "Good Game / Godly Gear", "category": "Slang" },
        { "acronym": "GGG", "definition": "Grinding Gear Games", "category": "Devs" },
        { "acronym": "GH", "definition": "Glacial Hammer", "category": "Skill" },
        { "acronym": "GMP", "definition": "Greater Multiple Projectiles", "category": "Support" },
        { "acronym": "GR", "definition": "Ghost Reaver", "category": "Keystone" },
        { "acronym": "GS", "definition": "Ground Slam", "category": "Skill" },
        { "acronym": "Gwennen", "definition": "Expedition Gambler", "category": "Mechanic" },
        { "acronym": "H/O", "definition": "Hideout", "category": "General" },
        { "acronym": "HC", "definition": "Hardcore", "category": "Mode" },
        { "acronym": "HFT", "definition": "Holy Flame Totem", "category": "Skill" },
        { "acronym": "HH", "definition": "Headhunter", "category": "Item" },
        { "acronym": "HoA", "definition": "Herald of Ash", "category": "Skill" },
        { "acronym": "HoAg", "definition": "Herald of Agony", "category": "Skill" },
        { "acronym": "HoI", "definition": "Herald of Ice", "category": "Skill" },
        { "acronym": "HoP", "definition": "Herald of Purity", "category": "Skill" },
        { "acronym": "HoT", "definition": "Herald of Thunder", "category": "Skill" },
        { "acronym": "HoWA", "definition": "Hand of Wisdom and Action", "category": "Item" },
        { "acronym": "HP", "definition": "Hit Points (Life)", "category": "Stat" },
        { "acronym": "IB", "definition": "Infernal Blow", "category": "Skill" },
        { "acronym": "IGN", "definition": "In-Game Name", "category": "Social" },
        { "acronym": "IIQ", "definition": "Increased Item Quantity", "category": "Stat" },
        { "acronym": "IIR", "definition": "Increased Item Rarity", "category": "Stat" },
        { "acronym": "IL / iLvl", "definition": "Item Level", "category": "Stat" },
        { "acronym": "Inquis", "definition": "Inquisitor", "category": "Class" },
        { "acronym": "IR", "definition": "Iron Reflexes", "category": "Keystone" },
        { "acronym": "Jew", "definition": "Jeweller's Orb", "category": "Currency" },
        { "acronym": "Jun", "definition": "Betrayal Master", "category": "Mechanic" },
        { "acronym": "KB", "definition": "Kinetic Blast", "category": "Skill" },
        { "acronym": "LA", "definition": "Lightning Arrow", "category": "Skill" },
        { "acronym": "LC", "definition": "Lightning Conduit", "category": "Skill" },
        { "acronym": "LF", "definition": "Looking For", "category": "Trade" },
        { "acronym": "LL", "definition": "Low Life", "category": "Mechanic" },
        { "acronym": "LMP", "definition": "Lesser Multiple Projectiles", "category": "Support" },
        { "acronym": "Login", "definition": "Excitement / Good Drop", "category": "Slang" },
        { "acronym": "LS", "definition": "Lightning Strike", "category": "Skill" },
        { "acronym": "MB", "definition": "Mageblood", "category": "Item" },
        { "acronym": "MF", "definition": "Magic Find", "category": "Mechanic" },
        { "acronym": "Mir", "definition": "Mirror of Kalandra", "category": "Currency" },
        { "acronym": "MoM", "definition": "Mind Over Matter", "category": "Keystone" },
        { "acronym": "MS", "definition": "Movement Speed / Molten Strike", "category": "Stat/Skill" },
        { "acronym": "MTX", "definition": "Microtransaction", "category": "General" },
        { "acronym": "Multi", "definition": "Crit Multiplier / Multistrike", "category": "Stat/Support" },
        { "acronym": "Necro", "definition": "Necromancer", "category": "Class" },
        { "acronym": "Niko", "definition": "Delve Master", "category": "Mechanic" },
        { "acronym": "Occ", "definition": "Occultist", "category": "Class" },
        { "acronym": "OOS", "definition": "Orb of Storms", "category": "Skill" },
        { "acronym": "OP", "definition": "Overpowered", "category": "Slang" },
        { "acronym": "PA", "definition": "Pain Attunement", "category": "Keystone" },
        { "acronym": "PB", "definition": "Point Blank / Petrified Blood", "category": "Key/Skill" },
        { "acronym": "PBoD", "definition": "Penance Brand of Dissipation", "category": "Skill" },
        { "acronym": "PC", "definition": "Price Check / Power Charge", "category": "Trade/Mech" },
        { "acronym": "PCoC", "definition": "Power Charge on Crit", "category": "Support" },
        { "acronym": "PConc", "definition": "Poisonous Concoction", "category": "Skill" },
        { "acronym": "pDPS", "definition": "Physical DPS", "category": "Stat" },
        { "acronym": "Pen", "definition": "Penetration", "category": "Stat" },
        { "acronym": "PF", "definition": "Pathfinder", "category": "Class" },
        { "acronym": "PK", "definition": "Player Kill (PVP/Griefing)", "category": "Slang" },
        { "acronym": "PoB", "definition": "Path of Building", "category": "Tool" },
        { "acronym": "Pop", "definition": "Explode (Bleed/Occultist)", "category": "Slang" },
        { "acronym": "PS", "definition": "Power Siphon", "category": "Skill" },
        { "acronym": "PT", "definition": "Precise Technique", "category": "Keystone" },
        { "acronym": "Q20", "definition": "20% Quality", "category": "Item" },
        { "acronym": "QotF", "definition": "Queen of the Forest", "category": "Item" },
        { "acronym": "Quant", "definition": "Item Quantity", "category": "Stat" },
        { "acronym": "Recomb", "definition": "Recombinator", "category": "Mechanic" },
        { "acronym": "Res", "definition": "Resistance", "category": "Stat" },
        { "acronym": "RF", "definition": "Righteous Fire", "category": "Skill" },
        { "acronym": "RIP", "definition": "Death", "category": "Slang" },
        { "acronym": "RMT", "definition": "Real Money Trade (Banned)", "category": "Trade" },
        { "acronym": "RNG", "definition": "Random Number Generator", "category": "General" },
        { "acronym": "RoA", "definition": "Rain of Arrows", "category": "Skill" },
        { "acronym": "Rog", "definition": "Expedition Crafter", "category": "Mechanic" },
        { "acronym": "Rota", "definition": "Rotation (Sharing maps)", "category": "Social" },
        { "acronym": "RT", "definition": "Resolute Technique", "category": "Keystone" },
        { "acronym": "Sabo", "definition": "Saboteur", "category": "Class" },
        { "acronym": "SA", "definition": "Scourge Arrow", "category": "Skill" },
        { "acronym": "SC", "definition": "Softcore / Standard", "category": "Mode" },
        { "acronym": "Scour", "definition": "Orb of Scouring", "category": "Currency" },
        { "acronym": "Shavs", "definition": "Shavronne's Wrappings", "category": "Item" },
        { "acronym": "Simu", "definition": "Simulacrum", "category": "Map" },
        { "acronym": "Slam", "definition": "Exalt Craft / Slam Skill", "category": "Craft/Skill" },
        { "acronym": "Snipe", "definition": "Trade Sniping / Snipe Skill", "category": "Trade/Skill" },
        { "acronym": "SQ", "definition": "The Squire", "category": "Item" },
        { "acronym": "SR", "definition": "Scorching Ray", "category": "Skill" },
        { "acronym": "SRS", "definition": "Summon Raging Spirit", "category": "Skill" },
        { "acronym": "SSF", "definition": "Solo Self-Found", "category": "Mode" },
        { "acronym": "SST", "definition": "Spectral Shield Throw", "category": "Skill" },
        { "acronym": "ST", "definition": "Spectral Throw", "category": "Skill" },
        { "acronym": "T1", "definition": "Tier 1 (Best Roll)", "category": "Crafting" },
        { "acronym": "T16", "definition": "Tier 16 Map", "category": "Map" },
        { "acronym": "T17", "definition": "Tier 17 Map (Uber)", "category": "Map" },
        { "acronym": "T4T", "definition": "Thanks for Trade", "category": "Trade" },
        { "acronym": "TFT", "definition": "The Forbidden Trove", "category": "Community" },
        { "acronym": "ToH", "definition": "Taste of Hate", "category": "Item" },
        { "acronym": "TP", "definition": "Town Portal", "category": "General" },
        { "acronym": "TR", "definition": "Toxic Rain", "category": "Skill" },
        { "acronym": "TS", "definition": "Tornado Shot", "category": "Skill" },
        { "acronym": "Tuyen", "definition": "Expedition Haggler", "category": "Mechanic" },
        { "acronym": "UE", "definition": "Uber Elder", "category": "Boss" },
        { "acronym": "UUE", "definition": "Uber Uber Elder", "category": "Boss" },
        { "acronym": "Vaal", "definition": "Vaal Orb / Skill", "category": "Currency" },
        { "acronym": "VLS", "definition": "Vaal Lightning Strike", "category": "Skill" },
        { "acronym": "VMS", "definition": "Vaal Molten Shell", "category": "Skill" },
        { "acronym": "VP", "definition": "Vaal Pact", "category": "Keystone" },
        { "acronym": "WED", "definition": "Weapon Elemental Damage", "category": "Support" },
        { "acronym": "Woke", "definition": "Awakened Gem / Orb", "category": "Item" },
        { "acronym": "WoC", "definition": "Wave of Conviction", "category": "Skill" },
        { "acronym": "WTB", "definition": "Want to Buy", "category": "Trade" },
        { "acronym": "WTS", "definition": "Want to Sell", "category": "Trade" },
        { "acronym": "WTT", "definition": "Want to Trade", "category": "Trade" },
        { "acronym": "zDPS", "definition": "Zero DPS", "category": "Build" },
        { "acronym": "zHP", "definition": "Zero HP (Deep Delve)", "category": "Build" },
        { "acronym": "ZO", "definition": "Zealot's Oath", "category": "Keystone" }
    ];

    data.forEach(item => {
        const record = new Record(collection);
        record.set("acronym", item.acronym);
        record.set("definition", item.definition);
        record.set("category", item.category);
        app.save(record);
    });

}, (app) => {
    const collection = app.findCollectionByNameOrId("abbreviations");
    app.delete(collection);
})
